default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  host: postgres
  port: 5432
  username: turo_tracker
  password: yourpassword

development:
  <<: *default
  database: turo_tracker_development

test:
  <<: *default
  database: turo_tracker_test

production:
  <<: *default
  database: turo_tracker_production
  username: turo_tracker
  password: <%= ENV['TURO_TRACKER_DATABASE_PASSWORD'] %>
